### ISSUE TITLE
Unable to connect to pods on different nodes in OpenStack

### ISSUE THREAD

**Issue by jimmidyson** [openshift/openshift-sdn#62]
We've set up a master & 2 nodes on OpenStack via openshift ansible (https://github.com/openshift/opnshift-ansible) & pods are created & assigned correct IPs depending on what node they are assigned to. Connecting to the pods on the same node works fine, but when you try to connect to a pod on another node it seems that there is no route set up. This is the same when you try to connect to a service with an endpoint pod on another host.

I can see no errors in OpenShift or SDN master/node logs. Is OpenShift SDN supposed to work properly on OpenStack?

**Comment by detiber** [comment]
While I haven't tested on OpenStack in particular, I ran into this issue
yesterday on AWS, and the fix was to add a rule to the security group that
allowed nodes to talk to each other over udp port 4789 (vxlan).

**Comment by jimmidyson** [comment]
In OpenStack we opened up all ports in the security group & no luck. I've tested with

    nc -u -v <node ip> 4789

& connection is established.

**Comment by detiber** [comment]
@jimmidyson I'll try to replicate the issue today and see if I can figure out what is happening.

**Comment by jimmidyson** [comment]
@detiber thanks! If you need access to our env to have a look around it's running on OS1 so let me know.

**Comment by detiber** [comment]
@jimmidyson could you provide your ansible inventory file? I want to make sure that I try to replicate your setup as closely as possible.

**Comment by jimmidyson** [comment]
@detiber this is what is in /etc/ansible/hosts:

```
# This is an example of a bring your own (byo) host inventory

[OSEv3:children]
masters
nodes

[OSEv3:vars]
deployment_type=enterprise
ansible_ssh_user=root
# Pre-release registry URL
#openshift_registry_url=docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-${component}:${version}
# Pre-release additional repo
#openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterprise/3.0/latest/RH7-RHOSE-3.0/$basearch/os', 'enabled': 1, 'gpgcheck': 0}]

# host group for masters
[masters]
beast-master.novalocal

# host group for nodes
[nodes]
beast-master.novalocal
beast-node[1:2].novalocal
```

**Comment by detiber** [comment]
@jimmidyson Still haven't gotten around to trying to reproduce it (I keep getting distracted with other tasks when I start to dig into it).

I see you have your inventory file referencing *.novalocal addresses? Where those issued from os1? All of my hosts get allocated *.os1.phx2.redhat.com addresses (which is another issue, since those are not resolvable externally.  Another thing I've noticed with os1 is that even the internal dns names are not resolvable from all internal hosts.

What you may have to do is override both openshift_hostname and openshift_public_hostname to either the associated ip address or otherwise manage the dns entries for external/internal fqdns for the hosts.

I'm not familiar with the configuration of OpenStack, so I'm not sure if these are limitations of the version/configuration of OpenStack we are using or if it is a misconfiguration of os1.

**Comment by jimmidyson** [comment]
@detiber Sorry I was wrong it wasn't actually running on os1, but on a standalone server with OpenStack set up on it. All hostnames resolve properly from all VMs by virtue of hosts file entries (not scalable I know, but should be functional at least).

Each minion has the following configuration for openshift-sdn-node, configured courtesy of openshift ansible:

    /usr/bin/openshift-sdn -minion -etcd-endpoints=https://beast-master.novalocal:4001 -public-ip=42.42.42.22 -v=4 -hostname=beast-master.novalocal -etcd-cafile=/etc/openshift/node/ca.crt -etcd-certfile=/etc/openshift/node/client.crt -etcd-keyfile=/etc/openshift/node/client.key

`public-IP` flag is correct on each minion.

So it looks like the flags you mentioned are already being set.

**Comment by jimmidyson** [comment]
@detiber Have you been able to look at this issue at all?

**Comment by rawlingsj** [comment]
Overriding the openshift variables in /etc/ansible/hosts solved the issue..

```
[masters]
master.novalocal openshift_hostname=master.novalocal openshift_ip={IP of private NIC} openshift_public_hostname=master.novalocal openshift_public_ip={IP of private NIC}

[nodes]
master.novalocal openshift_hostname=master.novalocal openshift_ip={IP of private NIC} openshift_public_hostname=master.novalocal openshift_public_ip={IP of private NIC}
node1.novalocal openshift_hostname=node1.novalocal openshift_ip={IP of private NIC} openshift_public_hostname=node1.novalocal openshift_public_ip={IP of private NIC}
node2.novalocal openshift_hostname=node2.novalocal openshift_ip={IP of private NIC} openshift_public_hostname=node2.novalocal openshift_public_ip={IP of private NIC}
```

**Comment by rawlingsj** [comment]
I was premature saying this was working by overriding the variables above.  I've just retested and there still seems to be the issue.  Overriding the variables does mean that an osc get pods shows all the pods across all nodes but that's not this issue here which I can only think I originally thought they were related as it was solved by https://github.com/openshift/training/blob/master/beta-3-setup.md#appendix---installing-in-iaas-clouds.

I currently have 1 master and two nodes.  Using the [hello-openshift example](https://gist.github.com/rawlingsj/cdaddac415148fe550e3) I have it running on node 1,  I've added a [service](https://gist.github.com/rawlingsj/b0ebbda57742af02e701) which I can successfully curl on node 1 

```
curl http://172.30.17.158:8080
Hello OpenShift!
```
but not master or node 2
```
curl http://172.30.17.158:8080
curl: (56) Recv failure: Connection reset by peer
```

**Comment by jimmidyson** [comment]
@rajatchopra Any thoughts on this? We discussed this on irc a little while back & you mentioned QE had successfully tested this. Do you have any details or contact for the setup?

**Comment by rawlingsj** [comment]
I've managed to get openshift running on the openstack instance we have.  I noticed a problem when testing the routes using dig..

`dig foo.beast.io`

was still resolving to 8.8.8.8 and not the master node.  

Now I'm sure what I've done is __not__ the answer but it's a start, I changed the /etc/resolv.conf for the two nodes that dnsmasq is not installed on to use the `lbr0` interface and I was able to successfully curl the hello_openshift service from all nodes.

I must admit I didnt connect the dnsmasq with kubernetes services, in my mind I thought dnsmasq was used for the openshift routes.

There must be a problem with the interface I originally set dnsmasq up on so will carry on looking but the problem seems to be solved.

**Comment by pruan-rht** [comment]
@jimmidyson @rawlingsj, my colleague @akostadinov got V3 to work on an Openstack installation in our MTV office server.  Unfortunately, he's out of the office until Monday.  I'll try your setup tonight and see if I'm seeing what you are reporting.

**Comment by akostadinov** [comment]
the instructions in beta3 training are to use `example.com` domain. If using another one, it's likely you missed places to change that domain. Or you didn't setup `resolv.conf` properly on nodes and/or your local machine.
I'd suggest you to start with newly created machines when doing further experiments as ansible is not good as far as I see in reverting previously incorrect changes. I mean if you run ansible once, then do modifications, then run again, it's highly likely that some changes do not get applied.

**Comment by rawlingsj** [comment]
thanks @akostadinov and @pruan-rht, this can probably be closed after my last comment.  It is working and it was because dnsmasq wasnt resolving correctly on the two nodes that didnt have it installed.  I changed the IP on master and node 2 to point to another interface that dnsmasq was listening on node 1 and it all worked even with the custom domain.

**Comment by jimmidyson** [comment]
Although this is working for us now, I guess this needs better documentation unless @rawlingsj you think you missed some bits of the documentation when you were installing?

**Comment by rawlingsj** [comment]
It would be great to have some docs explaining the role and dependency of DNS.  The only section I found was under the [router](https://github.com/openshift/origin/blob/master/docs/routing.md) and [router sharding](https://github.com/openshift/origin/blob/master/docs/router_sharding.md#dns) and my understanding now is that it is a requirement for any communication regardless of whether the router is being used or not (i.e kubernetes services).

I'm sure this will come with time but it helps to understand the interdependencies of these components when investigating problems.  Also we couldn't find any error messages so it took a while to investigate.

**Comment by jorgemoralespou** [comment]
We had similar issue, and the problem was that SkyDNS round robins requests to the available nameservers in /etc/resolv.conf.
In our case, just leaving one single entry (to dnsmasq server) on every node that does not have dnsmasq, and then on that server, has to have the public DNS server.

**Comment by pruan-rht** [comment]
FYI, I was able to do the same setup mentioned in the original post on our local Openstack installation.

**Comment by akostadinov** [comment]
+1, I think the documented dnsmasq setup relies on specific dnsmasq implementation and I also had some troubles figuring out what is the idea at the end. I think better instructions are to tell users setup dnsmasq or another DNS server as a recursive server with specific forwarders, instead of relying on resolv.conf content. Here is what I'd do with dnsmasq:
```
#echo DNS1=127.0.0.1 >> /etc/sysconfig/network-scripts/ifcfg-eth0
#for i in `grep ^nameserver /etc/resolv.conf | awk '{print $2}'`; do
#  echo server=$i >> /etc/dnsmasq.conf
#done
```
The above would put original DNS servers as forwarder in dnsmasq conf and have the dnsmasq server itself as the server in resolv.conf
